const SUPABASE_URL = "https://krhdqranidmepepyuxti.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyaGRxcmFuaWRtZXBlcHl1eHRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkwMDc1NTMsImV4cCI6MjEwNDU4MzU1M30.-EYb39lgDUfe3j1O64Z1mqEJUiuF-yD6wKbGz8TN6x8";
